name: fastapi  # Change this to your desired environment name
channels:
  - conda-forge
dependencies:
  - python=3.8.20
  - pytest
  - pytest-cov
  - fastapi
  - uvicorn
  - flake8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - joblib