name: fastapi
channels:
  - conda-forge
dependencies:
  - python=3.8.20
  - pytest
  - pytest-cov
  - fastapi=0.115.12
  - uvicorn=0.28.0
  - flake8
  - pip
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.6.1
  - joblib=1.3.2
  - requests=2.31.0
  - gunicorn=21.2.0
  - pydantic=2.6.4
  - starlette=0.46.2
  - httpx=0.28.1