name: CI on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 1) Main requirements (fastapi, sklearn, pandas, etc.)
          pip install -r ./starter/requirements.txt
          # 2) Test & lint tools
          pip install pytest pytest-cov flake8 httpx

      - name: Clean up pycache
        run: find . -type d -name "__pycache__" -exec rm -rf {} +

      - name: Run sanity checks
        run: |
          export PYTHONPATH=.
          echo "starter/test_main.py" | python ./starter/sanitycheck.py

      - name: Lint with Flake8
        run: flake8 ./starter --max-line-length=79

      - name: Run PyTest with coverage
        run: pytest ./starter -v --cov=./starter --cov-report=xml
