name: CI on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  run-ci:
    name: Run PyTest and Flake8
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: starter  # Tells all steps to use the starter folder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r ./starter/requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install FastAPI (which brings in the correct Starlette), plus test & lint deps
          pip install fastapi pytest pytest-cov flake8 httpx joblib pandas

      - name: Clean __pycache__
        run: find . -type d -name "__pycache__" -exec rm -rf {} +

      - name: Run sanity checks
        run: |
          # Ensure imports resolve to your local starter/ and not to site-packages
          export PYTHONPATH=.
          # Feed the path to your test_main.py into sanitycheck
          echo "starter/test_main.py" | python ./starter/sanitycheck.py
      
      - name: Run flake8
        run: flake8 ./starter --max-line-length=79

      - name: Run pytest
        run: pytest ./starter -v --cov=./starter --cov-report=xml