# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: Manual Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-ci:
    name: Run PyTest and Flake8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter  # Tells all steps to use the starter folder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 fastapi uvicorn
      
      - name: Run sanity fix
        run: echo 'starter/test_main.py' | PYTHONPATH=. python starter/sanitycheck.py

      - name: Run flake8
        run: flake8 ./starter --max-line-length=79

      - name: Run pytest
        run: pytest ./starter -v --cov=./starter --cov-report=xml